version: '3.8'
services:
  # --- Banco de Dados Centralizado (Em prod seria separado) ---
  postgres:
    image: postgres:16-alpine
    container_name: ecoshop-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecoshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Broker de Mensageria (Kafka) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ecoshop-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ecoshop-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- Observabilidade (Zipkin para Tracing Simples) ---
  zipkin:
    image: openzipkin/zipkin
    container_name: ecoshop-zipkin
    ports:
      - "9411:9411"

volumes:
  postgres_data: